name: apac_solution_challenge
description: APAC_solution_challenge Flutter project
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^5.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    -  assets/images/login_page_img.png
    -  assets/images/google_logo.png

