name: apac_solution_challenge
description: APAC_solution_challenge Flutter project
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  intl: ^0.17.0
=======
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^6.1.4

>>>>>>> 0c0f55effd66992f945c06c34c6f3bd1cfdb759a

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

assets:
  assets/images/

flutter:
  uses-material-design: true
  assets:
    -  assets/images/login_page_img.png
    -  assets/images/google_logo.png
    -  assets/images/login_choose_hobby_page.png
    -  assets/images/next_button.png
    -  assets/images/login_health_check_page.png

